on:
  push:
    branches:
      - master
name: Deploy Master
jobs:
  deploy-master:
    name: Deploy Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Filter master branch
        uses: actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da
        with:
          args: branch master
      - name: Docker Login
        uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build Image
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: build -t lichtblau/kraggl:master .
      - name: Push Image
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: push lichtblau/kraggl:master
      - name: Deploy Master
        uses: maddox/actions/ssh@6fc6694b013badc932fb2a6ec6edfa4e629254cf
        env:
          HOST: ${{ secrets.HOST }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          USER: ${{ secrets.USER }}
        with:
          args: cd proxy; ./deploy.js master