on:
  push:
    branches:
      - develop
name: Deploy Develop
jobs:
  deploy-develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Filter develop branch
        uses: actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da
        with:
          args: branch develop
      - name: Docker Login
        uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build Image
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: build -t lichtblau/kraggl:develop .
      - name: Push Image
        uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
        with:
          args: push lichtblau/kraggl:develop
      - name: Deploy Develop
        uses: maddox/actions/ssh@6fc6694b013badc932fb2a6ec6edfa4e629254cf
        env:
          HOST: ${{ secrets.HOST }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          USER: ${{ secrets.USER }}
        with:
          args: cd proxy; ./deploy.js develop