on:
  push:
    branches:
      - master
name: Deploy Master
jobs:
  deploy-master:
    name: Deploy Master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image
        run: docker build -t lichtblau/kraggl:master .
      - name: Push Image
        run: docker push lichtblau/kraggl:master
      - name: Deploy Master
        uses: maddox/actions/ssh@6fc6694b013badc932fb2a6ec6edfa4e629254cf
        env:
          HOST: ${{ secrets.HOST }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          USER: ${{ secrets.USER }}
        with:
          args: cd proxy; ./deploy.js master
